### ISSUE TITLE
wireframes

### ISSUE THREAD

**Issue by OliveLeb** [OliveLeb/news-website#1]
### wireframe desktop
![Web 1920 – 1](https://user-images.githubusercontent.com/59732862/100851705-d5f79780-3485-11eb-8136-e6d5e6ee68e5.png)

### Categorie
![Web 1920 – 3](https://user-images.githubusercontent.com/59732862/100851718-dabc4b80-3485-11eb-9e7b-72b58a8d48c7.png)

### Article
![Web 1920 – 2](https://user-images.githubusercontent.com/59732862/100851712-d8f28800-3485-11eb-9c14-161de8fbf465.png)

**Comment by Herondil** [comment]
Voici les remarques : 

1) Certains cadres n'ont pas vraiment l'air bien alignés, comme les articles sur le desktop.

2) Où doit-on cliquer pour accéder aux catégories ?

3) Enfin une remarque plus générale. Il est possible dans le wireframe de mettre du vrai texte et de vraies infos, par exemple ici je ne comprends pas ce qu'il y aurait à droite dans "aside".

**Comment by OliveLeb** [comment]
- Les cadres pas correctements alignés le seront. J'ai utilisé adobe xd et je suis pas très adroit dessus donc j'ai pas voulu trop perdre de temps.
- Dans aside, il y aura le formulaire de newsletter à chaque fois et une selection d'articles les plus lus, toutes catégories confondues pour la page home et relatif a la catégorie selectionnée dans la page catégorie et article.

**Comment by Herondil** [comment]
- Ok, pour valider un wireframe il faut que les éléments prévus alignés le soit complètement. Est-ce que tu as regardé si il y avait des outils de snapping ou de grille dans XD ?
- Et pour naviguer entre les catégories ?
